version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  default:

services:

  prometheus:
    image: napnap75/rpi-prometheus:prometheus
    depends_on:
      - cadvisor
      - node_exporter
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - default
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=10d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    # deploy:
    #   placement:
    #     constraints:
    #       - node.hostname == ${HOSTNAME}

  node_exporter:
    image: napnap75/rpi-prometheus:node_exporter
    #hostname: '{{.Node.Hostname}}'
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
#    deploy:
#      mode: global

  blackbox_exporter:
    image: napnap75/rpi-prometheus:blackbox_exporter
    restart: unless-stopped
    ports:
      - 9115:9115
    volumes:
      - ./blackbox:/config
#    deploy:
#      mode: global
    command:
      - '--config.file=/config/blackbox.yml'

  arm_exporter:
    image: carlosedp/arm_exporter
    #hostname: '{{.Node.Hostname}}'
    restart: unless-stopped
    ports:
      - 9243:9243
#    deploy:
#      mode: global

#  pihole_exporter:
#    image: bingenito/pihole-exporter
#    #hostname: '{{.Node.Hostname}}'
#    ports:
#      - 9311
#    command:
#      - '-log.level=debug'
#      #- '-pihole http://192.168.2.30'

  cadvisor:
    image: budry/cadvisor-arm:latest
    #image: unibaktr/cadvisor:linux-arm32v7-latest
    #hostname: '{{.Node.Hostname}}'
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/disk/:/var/disk:ro
#    deploy:
#      mode: global
    command:
       - --enable_load_reader=true
    #  - --global_housekeeping_interval=30s
    #  - --housekeeping_interval=5s
    #  - --storage_duration=1m0s

#  alertmanager:
#    image: napnap75/rpi-prometheus:alertmanager
#    restart: unless-stopped
#    ports:
#     - 9093:9093
#    volumes:
#     - ./alertmanager/:/etc/alertmanager/
#    command:
#     - '-config.file=/etc/alertmanager/config.yml'
#     - '-storage.path=/alertmanager'
    #deploy:
    #  placement:
    #    constraints:
    #- node.hostname == ${HOSTNAME}

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/plugins:/var/lib/grafana/plugins
    env_file:
      - config.monitoring
